/* eslint-disable no-unused-vars */
"use strict";
module.exports = {
  up: async (queryInterface, Sequelize) => {
    return queryInterface.bulkInsert(
      "PriorityWords",
      [
        {
          word_eng: "talk",
          word_kor: "말하다",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "say",
          word_kor: "말하다",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "speak",
          word_kor: "말하다",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "tell",
          word_kor: "말하다",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "give",
          word_kor: "주다",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "hand",
          word_kor: "손",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "get",
          word_kor: "갖다주다",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "live",
          word_kor: "살다",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "know",
          word_kor: "알다",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "make",
          word_kor: "만들다",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "manufacture",
          word_kor: "제조하다",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "understand",
          word_kor: "이해하다",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "listen",
          word_kor: "듣다",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "hear",
          word_kor: "듣다",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "carry",
          word_kor: "나르다",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "leave",
          word_kor: "놓다",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "appear",
          word_kor: "나타나다",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "find",
          word_kor: "찾다",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "seek",
          word_kor: "찾다",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "search",
          word_kor: "찾아보다",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "sit",
          word_kor: "앉다",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "leave",
          word_kor: "떠나다",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "buy",
          word_kor: "사다",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "get",
          word_kor: "얻다",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "read",
          word_kor: "읽다",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "feel",
          word_kor: "느끼다",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "call",
          word_kor: "부르다",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "use",
          word_kor: "쓰다",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "send",
          word_kor: "보내다",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "take",
          word_kor: "타다",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "ride",
          word_kor: "타고가다",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "ask",
          word_kor: "묻다",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "inquire",
          word_kor: "묻다",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "open",
          word_kor: "열다",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "appreciate",
          word_kor: "감사하다",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "drop",
          word_kor: "떨어뜨리다",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "fall",
          word_kor: "떨어지다",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "drip",
          word_kor: "떨어지다",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "drop",
          word_kor: "내려주다",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "separate",
          word_kor: "나누다",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "distinguish",
          word_kor: "구별하다",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "notice",
          word_kor: "알아차리다",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "delay",
          word_kor: "미루다",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "excited",
          word_kor: "신난",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "flattered",
          word_kor: "우쭐해진",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "exhausted",
          word_kor: "탈진한",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "sad",
          word_kor: "슬픈",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "nervous",
          word_kor: "긴장한",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "disappointed",
          word_kor: "실망한",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "stubborn",
          word_kor: "답답한",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "small",
          word_kor: "좁은",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "serious",
          word_kor: "진지한",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "confused",
          word_kor: "혼란스러운",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "unfair",
          word_kor: "부당한",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "bother",
          word_kor: "괴롭히다",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "worry",
          word_kor: "걱정시키다",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "beat",
          word_kor: "때리다",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "ground",
          word_kor: "땅",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "wonder",
          word_kor: "궁금해하다",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "apologize",
          word_kor: "사과하다",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "anytime",
          word_kor: "언제든지",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "offend",
          word_kor: "불쾌하게하다",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "mean",
          word_kor: "의도하다",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "humble",
          word_kor: "겸손한",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "modest",
          word_kor: "겸손한",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "brag",
          word_kor: "잘난척하다",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "arrogant",
          word_kor: "거만한",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "cheap",
          word_kor: "인색한",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "outgoing",
          word_kor: "사교적인",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "quiet",
          word_kor: "조용한",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "talkative",
          word_kor: "수다스러운",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "rude",
          word_kor: "무례한",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "polite",
          word_kor: "공손한",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "cunning",
          word_kor: "교활한",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "honest",
          word_kor: "정직한",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "mean",
          word_kor: "심술굳은",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "coward",
          word_kor: "겁쟁이",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "brave",
          word_kor: "용감한",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "guts",
          word_kor: "배짱",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "selfish",
          word_kor: "이기적인",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "thoughtful",
          word_kor: "사려깊은",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "considerate",
          word_kor: "배려하는",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "sweet",
          word_kor: "달콤한",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "shy",
          word_kor: "수줍은",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "humorous",
          word_kor: "재미있는",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "boring",
          word_kor: "지루한",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "quiet",
          word_kor: "얌전한",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "rebellious",
          word_kor: "반항적인",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "spoiled",
          word_kor: "버릇없는",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "grumpy",
          word_kor: "심술궃은",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "masculine",
          word_kor: "남자같은",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "overweight",
          word_kor: "과체중의",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "fit",
          word_kor: "건강한",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "skinny",
          word_kor: "마른",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "handsome",
          word_kor: "잘생긴",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "semester",
          word_kor: "학기",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "assignment",
          word_kor: "과제",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "copy",
          word_kor: "복사",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "borrow",
          word_kor: "빌리다",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "explain",
          word_kor: "설명하다",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "apply",
          word_kor: "신청하다",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "accurate",
          word_kor: "정확한",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "clear",
          word_kor: "명확한",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "profound",
          word_kor: "깊은",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "graduate",
          word_kor: "졸업하다",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "period",
          word_kor: "교시",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "join",
          word_kor: "입사하다",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "quit",
          word_kor: "그만두다",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "fire",
          word_kor: "해고하다",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "finish",
          word_kor: "끝내다",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "submit",
          word_kor: "제출하다",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "document",
          word_kor: "서류",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "analyze",
          word_kor: "분석하다",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "define",
          word_kor: "정의하다",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "negotiate",
          word_kor: "협상하다",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "reply",
          word_kor: "답변",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "resume",
          word_kor: "재개하다",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "shift",
          word_kor: "옮기다",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "retire",
          word_kor: "은퇴하다",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "bend",
          word_kor: "구부리다",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "stretch",
          word_kor: "뻗다",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "sweat",
          word_kor: "땀",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "text",
          word_kor: "글",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "save",
          word_kor: "저장하다",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "press",
          word_kor: "누르다",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "block",
          word_kor: "막다",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "post",
          word_kor: "우편",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "browse",
          word_kor: "둘러보다",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "fit",
          word_kor: "맞추다",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "wrap",
          word_kor: "싸다",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "exchange",
          word_kor: "교환",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "purchase",
          word_kor: "구매",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "recommend",
          word_kor: "추천하다",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "wait",
          word_kor: "기다리다",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "order",
          word_kor: "주문하다",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "have",
          word_kor: "가지다",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "sell",
          word_kor: "팔다",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "change",
          word_kor: "바꾸다",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "receipt",
          word_kor: "영수증",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "flirt",
          word_kor: "작업걸다",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "dump",
          word_kor: "차다",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "argue",
          word_kor: "다투다",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "good",
          word_kor: "화해한",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "break",
          word_kor: "부러지다",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "sprain",
          word_kor: "삐다",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "hurt",
          word_kor: "아프다",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "sick",
          word_kor: "아픈",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "painkiller",
          word_kor: "진통제",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "clinic",
          word_kor: "병원",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "pharmacy",
          word_kor: "약국",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "symptom",
          word_kor: "증상",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "deposit",
          word_kor: "예금",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "account",
          word_kor: "장부",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "mortgage",
          word_kor: "대출",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "digit",
          word_kor: "자릿수",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "form",
          word_kor: "형식",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "wire",
          word_kor: "철사",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "fee",
          word_kor: "요금",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "branch",
          word_kor: "나뭇가지",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "crosswalk",
          word_kor: "횡단보도",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "sign",
          word_kor: "서명하다",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "traffic",
          word_kor: "교통",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "shortcut",
          word_kor: "지름길",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "vacuum",
          word_kor: "진공",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "mop",
          word_kor: "대걸레",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "sweep",
          word_kor: "쓸다",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "rub",
          word_kor: "문지르다",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "wipe",
          word_kor: "닦다",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "scrub",
          word_kor: "문지르다",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "smell",
          word_kor: "냄새나다",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "dusty",
          word_kor: "먼지많은",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "trash",
          word_kor: "쓰레기",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "recycle",
          word_kor: "재활용하다",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "stain",
          word_kor: "얼룩",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "mold",
          word_kor: "곰팡이",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "bully",
          word_kor: "괴롭히다",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "demanding",
          word_kor: "까다로운",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "silly",
          word_kor: "어리석은",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "ignore",
          word_kor: "무지하다",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "tolerate",
          word_kor: "참다",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "blame",
          word_kor: "탓하다",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "fault",
          word_kor: "잘못",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "devastated",
          word_kor: "망연자실한",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "attack",
          word_kor: "공격하다",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "slice",
          word_kor: "썰다",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "dice",
          word_kor: "깍둑썰다",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "spread",
          word_kor: "펴바르다",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "season",
          word_kor: "양념하다",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "dip",
          word_kor: "담그다",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "marinate",
          word_kor: "재워놓다",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "ferment",
          word_kor: "발효시키다",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "keep",
          word_kor: "보관하다",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "outside",
          word_kor: "밖",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "sprinkle",
          word_kor: "뿌리다",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "peel",
          word_kor: "껍질까다",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "stove",
          word_kor: "가스레인지",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "microwave",
          word_kor: "전자레인지",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "drain",
          word_kor: "빠지다",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "simmer",
          word_kor: "끓다",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "remove",
          word_kor: "제거하다",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "watery",
          word_kor: "묽은",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "thick",
          word_kor: "걸쭉한",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "bland",
          word_kor: "싱거운맛",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "flaver",
          word_kor: "맛",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "crispy",
          word_kor: "바삭바삭한",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "refreshing",
          word_kor: "개운한",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "spicy",
          word_kor: "매운",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "sugary",
          word_kor: "달콤한",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "fatty",
          word_kor: "지방",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "disgusting",
          word_kor: "역겨운",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "better",
          word_kor: "더나은",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "try",
          word_kor: "해보다",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "chew",
          word_kor: "씹다",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "swallow",
          word_kor: "삼키다",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "sometimes",
          word_kor: "가끔",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "usually",
          word_kor: "보통",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "probably",
          word_kor: "아마",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "absolutely",
          word_kor: "확실히",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "definitely",
          word_kor: "확실히",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "rarely",
          word_kor: "드문",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "recently",
          word_kor: "최근에",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "currently",
          word_kor: "현재",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "immediately",
          word_kor: "즉시",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "fortunately",
          word_kor: "다행히",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "basically",
          word_kor: "기본적으로",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "eventually",
          word_kor: "결국",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "initially",
          word_kor: "처음에",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "actually",
          word_kor: "사실",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "exactly",
          word_kor: "정확히",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "certainly",
          word_kor: "확실히",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "regularly",
          word_kor: "정기적으로",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "constantly",
          word_kor: "거듭",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "expecially",
          word_kor: "특별히",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "typically",
          word_kor: "보통",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "boarding",
          word_kor: "탑승",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "fragile",
          word_kor: "연약한",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "travel",
          word_kor: "여행",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "trip",
          word_kor: "여행",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "tour",
          word_kor: "여행",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "flight",
          word_kor: "비행",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "delay",
          word_kor: "연기",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "destination",
          word_kor: "도착지",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "pack",
          word_kor: "포장하다",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "unpack",
          word_kor: "꺼내다",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "extra",
          word_kor: "여분의",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "contact",
          word_kor: "연락하다",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "lose",
          word_kor: "잃어버리다",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "seat",
          word_kor: "좌석",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "aisle",
          word_kor: "통로",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "switch",
          word_kor: "전환",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "store",
          word_kor: "상점",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "limit",
          word_kor: "제한",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "change",
          word_kor: "변화",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "domestic",
          word_kor: "국내의",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "international",
          word_kor: "국제적인",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "baggage",
          word_kor: "짐",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "passport",
          word_kor: "여권",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "arrive",
          word_kor: "도착하다",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "depart",
          word_kor: "출발하다",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "permitted",
          word_kor: "허가된",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "prohibited",
          word_kor: "금지된",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "throw",
          word_kor: "열다",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "appreciate",
          word_kor: "인정하다",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "immigration",
          word_kor: "이민",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "customs",
          word_kor: "세관",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "declare",
          word_kor: "신고하다",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "occupation",
          word_kor: "직업",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "nationality",
          word_kor: "국적",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "purpose",
          word_kor: "목적",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "bring",
          word_kor: "가져오다",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "stay",
          word_kor: "머무르다",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "sightseeing",
          word_kor: "관광",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "repeat",
          word_kor: "반복하다",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "nearest",
          word_kor: "근접한",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "reserve",
          word_kor: "예약하다",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "souvenir",
          word_kor: "기념품",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "discount",
          word_kor: "할인",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "allowed",
          word_kor: "허가된",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "withdraw",
          word_kor: "출금하다",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "confirm",
          word_kor: "확인하다",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "entrance",
          word_kor: "입구",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "last",
          word_kor: "지속되다",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "break",
          word_kor: "부수다",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "party",
          word_kor: "단체",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "exhibit",
          word_kor: "전시하다",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "probide",
          word_kor: "주다",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "crowded",
          word_kor: "붐비는",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "celebrate",
          word_kor: "기념하다",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "station",
          word_kor: "역",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "stop",
          word_kor: "멈추다",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "catch",
          word_kor: "잡다",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "cost",
          word_kor: "비용",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "keep",
          word_kor: "유지하다",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "rent",
          word_kor: "빌리다",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "rate",
          word_kor: "요금",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "include",
          word_kor: "포함하다",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "insert",
          word_kor: "넣다",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "fine",
          word_kor: "좋은",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "miss",
          word_kor: "놓치다",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "transfer",
          word_kor: "환승하다",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "request",
          word_kor: "요청하다",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "work",
          word_kor: "작동하다",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "smoking",
          word_kor: "흡연",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "upgrade",
          word_kor: "개선시키다",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "complimentary",
          word_kor: "무료의",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "serve",
          word_kor: "제공하다",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "extend",
          word_kor: "늘리다",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "deposit",
          word_kor: "보증금",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "local",
          word_kor: "지역의",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "tax",
          word_kor: "세금",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "cash",
          word_kor: "돈",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "return",
          word_kor: "돌려주다",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "buck",
          word_kor: "달러",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "suit",
          word_kor: "어울리다",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "popular",
          word_kor: "대중적인",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "cheap",
          word_kor: "싼",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "affordable",
          word_kor: "저렴한",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "expensive",
          word_kor: "비싼",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "coupon",
          word_kor: "쿠폰",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "measure",
          word_kor: "재다",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "prefer",
          word_kor: "선호하다",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "swipe",
          word_kor: "긁다",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "warranty",
          word_kor: "품질보증서",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "decide",
          word_kor: "정하다",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "patio",
          word_kor: "테라스",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "special",
          word_kor: "특별한",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "tip",
          word_kor: "봉사료",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "full",
          word_kor: "배부른",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "check",
          word_kor: "계산서",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "together",
          word_kor: "같이",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "separate",
          word_kor: "분리된",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "split",
          word_kor: "나누다",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "taken",
          word_kor: "주인있는",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "cancel",
          word_kor: "취소하다",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "share",
          word_kor: "나누다",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "crave",
          word_kor: "열망하다",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "perfect",
          word_kor: "완벽한",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "cellphone",
          word_kor: "휴대폰",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "fries",
          word_kor: "감자튀김",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "studio",
          word_kor: "작업실",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "outlet",
          word_kor: "할인점",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "stapler",
          word_kor: "스테이플러",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "cheating",
          word_kor: "부정행위",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "gym",
          word_kor: "체육관",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "treadmill",
          word_kor: "런닝머신",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "horn",
          word_kor: "경적",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "laptop",
          word_kor: "노트북",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "apartment",
          word_kor: "아파트",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "introduce",
          word_kor: "소개하다",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "age",
          word_kor: "나이",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "invite",
          word_kor: "초대하다",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "join",
          word_kor: "합류하다",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "close",
          word_kor: "친한",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "see",
          word_kor: "보다",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "sometime",
          word_kor: "언젠가",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "grab",
          word_kor: "쥐다",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "familiar",
          word_kor: "익숙한",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "pronounce",
          word_kor: "발음하다",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "rough",
          word_kor: "힘든",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "sober",
          word_kor: "맨정신의",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "calendar",
          word_kor: "달력",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "day",
          word_kor: "하루",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "date",
          word_kor: "날짜",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "sleep",
          word_kor: "자다",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "holiday",
          word_kor: "휴일",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "sharp",
          word_kor: "날카로운",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "rain",
          word_kor: "비",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "melt",
          word_kor: "녹다",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "breeze",
          word_kor: "바람",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "gorgeous",
          word_kor: "아름다운",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "stay",
          word_kor: "유지하다",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "gloomy",
          word_kor: "우울한",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "season",
          word_kor: "계절",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "grateful",
          word_kor: "고마워하는",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "sincerely",
          word_kor: "진심으로",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "compliment",
          word_kor: "칭찬하다",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "mistake",
          word_kor: "실수",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "find",
          word_kor: "찾다",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "upset",
          word_kor: "속상한",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "angry",
          word_kor: "화난",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "mad",
          word_kor: "미친",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "disappointing",
          word_kor: "실망스러운",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "sensitive",
          word_kor: "예민한",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "mature",
          word_kor: "성숙한",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "attractive",
          word_kor: "매력있는",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "oprimistic",
          word_kor: "낙천적인",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "picky",
          word_kor: "까다로운",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "calm",
          word_kor: "차분한",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "embarrassed",
          word_kor: "당황한",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "frustrated",
          word_kor: "불만스러운",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "humiliated",
          word_kor: "굴욕적인",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "home",
          word_kor: "집",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "house",
          word_kor: "집",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "fridge",
          word_kor: "냉장고",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "drawer",
          word_kor: "서랍",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "bathroom",
          word_kor: "욕실",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "closet",
          word_kor: "옷장",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "sink",
          word_kor: "싱크대",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "organize",
          word_kor: "체계화하다",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "dishwasher",
          word_kor: "식기세척기",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "detergent",
          word_kor: "세제",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "kitchen",
          word_kor: "부엌",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "garage",
          word_kor: "차고",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "neighborhood",
          word_kor: "동네",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "downstairs",
          word_kor: "아래층에",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "upstairs",
          word_kor: "위층에",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "bedroom",
          word_kor: "침실",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "livingroom",
          word_kor: "거실",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "comfy",
          word_kor: "편안한",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "cozy",
          word_kor: "아늑한",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "stairs",
          word_kor: "계단",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "elevator",
          word_kor: "엘리베이터",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "flawless",
          word_kor: "흠없는",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "watch",
          word_kor: "조심하다",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "sore",
          word_kor: "따가운",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "itchy",
          word_kor: "가려운",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "swollen",
          word_kor: "부어오른",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "recap",
          word_kor: "요약하다",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "attach",
          word_kor: "붙이다",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "deadline",
          word_kor: "마감기한",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "busy",
          word_kor: "바쁜",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "attend",
          word_kor: "참석하다",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "papers",
          word_kor: "서류",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "set",
          word_kor: "정하다",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "neat",
          word_kor: "멋진",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "thorough",
          word_kor: "철저한",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "start",
          word_kor: "시작하다",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "end",
          word_kor: "끝나다",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "company",
          word_kor: "회사",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "smell",
          word_kor: "냄새",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "place",
          word_kor: "장소",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "toasted",
          word_kor: "구운",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "refreshments",
          word_kor: "다과",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "cook",
          word_kor: "요리하다",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "portion",
          word_kor: "몫",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "hobby",
          word_kor: "취미",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "collect",
          word_kor: "모으다",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "write",
          word_kor: "쓰다",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "sing",
          word_kor: "노래하다",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "favorite",
          word_kor: "좋아하는",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "lend",
          word_kor: "빌려주다",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "merry",
          word_kor: "결혼하다",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "discuss",
          word_kor: "토론하다",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "quit",
          word_kor: "떠나다",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "improve",
          word_kor: "나아지다",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "doable",
          word_kor: "가능한",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          word_eng: "priceless",
          word_kor: "소중한",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
      ],
      {}
    );
  },
  down: async (queryInterface, Sequelize) => {
    const Op = Sequelize.Op;
    return queryInterface.bulkDelete(
      "PriorityWords",
      {
        word_eng: {
          [Op.in]: ["give", "who", "use", "right"],
        },
      },
      {}
    );
  },
};
