/* eslint-disable no-unused-vars */
"use strict";
module.exports = {
  up: async (queryInterface, Sequelize) => {
    return queryInterface.bulkInsert(
      "user_priority_words",
      [
        {
          user_id: 1,
          priority_word_id: 1,
          distinguish: 99,
          check_in: null,
          check_out: null,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          user_id: 1,
          priority_word_id: 2,
          distinguish: 0,
          check_in: null,
          check_out: null,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          user_id: 1,
          priority_word_id: 3,
          distinguish: 1,
          check_in: null,
          check_out: null,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          user_id: 1,
          priority_word_id: 4,
          distinguish: 3,
          check_in: null,
          check_out: null,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          user_id: 1,
          priority_word_id: 5,
          distinguish: 7,
          check_in: null,
          check_out: null,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          user_id: 1,
          priority_word_id: 1,
          distinguish: 99,
          check_in: null,
          check_out: null,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          user_id: 1,
          priority_word_id: 2,
          distinguish: 0,
          check_in: null,
          check_out: null,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          user_id: 1,
          priority_word_id: 3,
          distinguish: 1,
          check_in: null,
          check_out: null,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          user_id: 1,
          priority_word_id: 4,
          distinguish: 3,
          check_in: null,
          check_out: null,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          user_id: 1,
          priority_word_id: 5,
          distinguish: 7,
          check_in: null,
          check_out: null,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          user_id: 2,
          priority_word_id: 1,
          distinguish: 99,
          check_in: null,
          check_out: null,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          user_id: 2,
          priority_word_id: 2,
          distinguish: 0,
          check_in: null,
          check_out: null,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          user_id: 2,
          priority_word_id: 3,
          distinguish: 1,
          check_in: null,
          check_out: null,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          user_id: 2,
          priority_word_id: 4,
          distinguish: 3,
          check_in: null,
          check_out: null,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          user_id: 2,
          priority_word_id: 5,
          distinguish: 7,
          check_in: null,
          check_out: null,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          user_id: 3,
          priority_word_id: 1,
          distinguish: 99,
          check_in: null,
          check_out: null,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          user_id: 3,
          priority_word_id: 2,
          distinguish: 0,
          check_in: null,
          check_out: null,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          user_id: 3,
          priority_word_id: 3,
          distinguish: 1,
          check_in: null,
          check_out: null,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          user_id: 3,
          priority_word_id: 4,
          distinguish: 3,
          check_in: null,
          check_out: null,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          user_id: 3,
          priority_word_id: 5,
          distinguish: 7,
          check_in: null,
          check_out: null,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          user_id: 4,
          priority_word_id: 1,
          distinguish: 99,
          check_in: null,
          check_out: null,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          user_id: 4,
          priority_word_id: 2,
          distinguish: 0,
          check_in: null,
          check_out: null,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          user_id: 4,
          priority_word_id: 3,
          distinguish: 1,
          check_in: null,
          check_out: null,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          user_id: 4,
          priority_word_id: 4,
          distinguish: 3,
          check_in: null,
          check_out: null,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          user_id: 4,
          priority_word_id: 5,
          distinguish: 7,
          check_in: null,
          check_out: null,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
      ],
      {}
    );
  },
  down: async (queryInterface, Sequelize) => {
    const Op = Sequelize.Op;
    return queryInterface.bulkDelete(
      "PriorityWords",
      {
        word_eng: {
          [Op.in]: ["one", "two", "three", "four"],
        },
      },
      {}
    );
  },
};
